### ISSUE TITLE
Encoding using OP_CHECKMULTISIG

### ISSUE THREAD

**Issue by stoicism2323** [paulkernfeld/burn-stream#1]
It looks to me like currently burn-stream and burn-stream-writer only support OP_RETURN. OP_CHECKMULTISIG support is necessary I think because it's not prunable, therefore allows the burn stream to be truly immutable. What are your thoughts on this? Thanks!

**Comment by paulkernfeld** [comment]
I don't think this should be a problem, but I might be misunderstanding how pruning works, or which kind of pruning you're talking about. My understanding is that full Bitcoin clients usually have two databases:
1. The blockchain itself. That is, a map from block hash to the contents of each block.
2. The UTXO database. That is, a map from Bitcoin address to the amount of Bitcoin left in this address.

As far as the blockchain, a full node won't prune anything because it needs the entire contents of each block in order to verify the hash of that block.

I believe that the UTXO database is where pruning happens. Since OP_RETURN makes an unspendable output, you are right that burn-stream information won't be stored in the UTXO database. However, burn-stream should work fine despite this, since we can retrieve transactions by looking through the blockchain.

Does this seem right? Are there important advantages to making sure that data is stored in the UTXO database?

**Comment by stoicism2323** [comment]
Thanks for the response Paul. That makes a lot of sense. I've just heard that op_return is prunable so counterparty needs to use op_multisig or pubkeyhash. I need to find out if they only use it BC they need the utxo mempool. Or if there is some weirdness like a TX that is not in the mempool is technically censorable by someone.... Or I'm being an idiot (most likely) and this project is fine just using op return

**Comment by paulkernfeld** [comment]
Hmm, I am actually using P2PKH as well as OP_RETURN. Each transaction has at least two outputs: one is P2PKH, the other is an OP_RETURN. I would be interested to hear what you find out, though! It's not too late to modify this to use a different way to encode data.

**Comment by stoicism2323** [comment]
Thanks Paul. I just asked counterparty dev Chris Derose what the problem is with why counterparty txes need to be in the UTXO pool (main memory), he said:

op_return is trivially prunable. It relies on the empathy of the relays to transmit
whereas the txos are required to reconstruct consensus
if you don't keep the txo's you're at risk of being unable to maintain consensus
whereas op_return is triviallly discarded without penalty

I am not sure if this is an issue with counterparty consensus or bitcoin consensus... will find out more

**Comment by paulkernfeld** [comment]
Yeah... this seems like something to investigate. I have a couple questions about this:
- What is the "UTXO pool (main memory)?" I'm guessing this is referring to the pool of unconfirmed Bitcoin transactions?
- "if you don't keep the txo's" <- in this case, who is deciding whether to keep or not keep TXOs, and where are they keeping them?
- "op_return is triviallly discarded without penalty" <- where can OP_RETURN be discarded from without penalty?

**Comment by stoicism2323** [comment]
1. UTXO pool is the data that miners must keep in main memory to avoid DOS attacks I believe. Gavin says in his blog post 'UTXO Uh Oh':

"If you are mining, then taking longer to validate new blocks puts you at a disadvantage, because you can’t (or, at least, shouldn’t) start mining on the new best chain until you’ve fully validated the new block."

Addressing 2 and 3. The issue and what is meant by 'OP_RETURN data is prunable' is I believe that only the hash of the OP_RETURN data is stored in the blockchain and the actual data itself, because it is encoded as a transaction output, is OK to be pruned from the UTXO pool by full nodes and miners. Even if the UTXO pool does not have to be put kept in main mem, this is still an issue. The only thing that full nodes are forced to store is the hash of the data, rather than the data itself. This means that the actual data will have to be stored elsewhere, if we want to guarantee that the data is uncensorable. In which case OP_RETURN only guarantees us that we will be able to validate that the same data existed on the date in which the tx was created, as we cannot retrieve the data from the blockchain itself. We have to assume that all full nodes and miners will prune the OP_RETURN tx output data eventually, simply because they can therefore they will be forced to eventually thanks to economic or gov pressures. (Imagine illegal content being stored as OP_RETURN... any honest full node would like to prune that from his UTXO pool. He's ok with just the hash being on his blockchain tho.)

I am still trying to figure this out... This brings me to the question of, is there some way to store the actual DATA itself on the blockchain and not just the hash of it? Even if it's very expensive to do so? Thanks for brainstorming this issue with me, and of course I may be wrong abt a lot here, and this project may have nothing to worry about with using OP_RETURN, especially if hypercore can be used for all data storage needs.

**Comment by stoicism2323** [comment]
Actually I think I was misunderstanding things again... I don't think there's an issue with using OP_RETURN here. For some projects there may be some censorship risks in the future but right now it looks like OP_RETURN does encode data directly into the blockchain so it's not an issue for proof of burn. I was wrong abt the hash thing, I think I got confused bc that's how counterparty does it.

**Comment by paulkernfeld** [comment]
Thanks for all that information, I learned a lot about OP_RETURN!

Yeah, I agree that there might be censorship risks in the future, but right now I think OP_RETURN should be all right. Personally, I doubt that full nodes will ever make a move to prune data in OP_RETURNs, because people will just move to store data using OP_CHECKMULTISIG, which will end up being a lose-lose because it's just a less efficient way to store data.
